// app/_components/Square/index.tsx
'use client'
import Image from 'next/image'
import squareImage from './square.jpg'
import { useState } from 'react'
import { motion } from 'framer-motion'

export default function Square() {
  const [loaded, setLoaded] = useState(false)
  return (
    <motion.div
      className="max-w-3xl"
      initial="hidden"
      animate={loaded ? 'visible' : 'hidden'}
      variants={{
        hidden: { opacity: 0 },
        visible: { opacity: 1 },
      }}
      transition={{ duration: 1, ease: 'easeOut' }}
    >
      <figure className="animate-beat">
        <Image
          src={squareImage}
          alt="Ripples On Earth"
          priority
          width={1024}
          height={1024}
          loading="eager"
          onLoad={() => setLoaded(true)}
        />
        <figcaption className="-translate-x-[0.4rem] -translate-y-6 text-right font-neutral text-base font-bold sm:-translate-y-7 sm:text-xl">
          Software Engineer
        </figcaption>
      </figure>
    </motion.div>
  )
}

// src/lib/components/Square.svelte
<script lang="ts">
  import { animate } from 'motion'

  let containerElement = $state<HTMLDivElement>()
  $effect(() => {
    if (!containerElement) return
    animate(containerElement, { opacity: 1 }, { ease: 'easeOut', duration: 1 })
  })
</script>

<div class="relative">
  <div class="flex w-full justify-center sm:pt-8">
    <div bind:this={containerElement} class="max-w-3xl opacity-0">
      <figure class="animate-beat">
        <img
          width={768}
          height={768}
          src="/square.jpg"
          alt="Ripples on Earth"
          loading="eager"
        />
        <figcaption
          class="-translate-x-[0.4rem] -translate-y-7 text-right font-neutral text-xl font-bold sm:-translate-y-9 sm:text-3xl"
        >
          Software Engineer
        </figcaption>
      </figure>
    </div>
  </div>
  <div
    class="absolute left-2 top-2 font-neutral text-[16vw] leading-none sm:left-0 sm:top-0 lg:text-[12rem]"
  >
    <h1 class="font-bold">Dennis</h1>
    <h1 class="font-bold">Eum</h1>
  </div>
</div>

<style>
  @keyframes beat {
    0% {
      opacity: 0.4;
    }
    60% {
      opacity: 0.8;
    }
    100% {
      opacity: 0.4;
    }
  }
  .animate-beat {
    animation: beat 6s cubic-bezier(0.4, 0, 0.6, 1) infinite;
  }
</style>
